-- vim: set filetype=lua :
-- NOTE: Do not edit this file directly
-- Use: chezmoi edit ~/.config/nvim/init.lua

-- Allow for when user may not be able to write to $HOME
if vim.env.NVIM_NO_PERSIST then
  vim.o.shadafile  = "NONE"   -- no shada/viminfo
  vim.o.swapfile   = false
  vim.o.undofile   = false
  vim.o.backup     = false
  vim.o.writebackup= false
end

if not vim.env.NVIM_DISABLE_PLUGINS then
  require("plugins")
  require("load_lspconfig")
  require("load_treesitter")
  require("load_lualine")
  require("load_gitsigns")
end

do
  local ok = pcall(require, 'lualine')
  if not ok then
    vim.g.use_glyphs = false
    local function is_console()
      if vim.fn.has('gui_running') == 1 then return false end
      local term = vim.env.TERM or ''
      if term == 'linux' or term == 'vt100' then return true end
      local has_display = vim.env.DISPLAY or vim.env.WAYLAND_DISPLAY
      local fancy = term:match('xterm') or term:match('tmux') or term:match('kitty')
        or term:match('alacritty') or term:match('wezterm') or term:match('foot')
        or term:match('screen')
      if not has_display and not fancy then return true end
      return false
    end
    vim.g.use_glyphs = not is_console()
    if vim.env.NVIM_DISABLE_GLYPHS then
      vim.g.use_glyphs = false
    end

    require('mystatusline')
  end
end

do
  local ok = pcall(require, 'nightfly')
  if not ok then
    vim.cmd("colorscheme lunaperche")
  end
end

require("autocmds")
require("keymaps")
require("options")

