#!/bin/sh

# Sync my dotfiles into the dotfiles repo
unset DOTFILES
DOTFILES="$DOTFILES $HOME/.config/local/waybar*"
DOTFILES="$DOTFILES $HOME/.config/local/wb_*"
DOTFILES="$DOTFILES $HOME/.config/niri/config.kdl"
DOTFILES="$DOTFILES $HOME/.config/niri/scripts"
DOTFILES="$DOTFILES $HOME/.config/nvim"
DOTFILES="$DOTFILES $HOME/.config/waybar"
DOTFILES="$DOTFILES $HOME/.bashrc"
DOTFILES="$DOTFILES $HOME/.merdely.profile"
DOTFILES="$DOTFILES $HOME/.vimrc"

dest_dir=$(dirname "$(realpath "$0")")

for dotfile in $DOTFILES; do
  relative_path=${dotfile/$HOME\//}
  mkdir -p "$dest_dir"/"$(dirname "$relative_path")"
  rsync -a --info=NAME "$dotfile" "$dest_dir"/"$(dirname "$relative_path")"
done
