#!/bin/sh

# Sync my dotfiles into the dotfiles repo
unset DOTFILES
DOTFILES="$DOTFILES $HOME/.config/local/waybar*"
DOTFILES="$DOTFILES $HOME/.config/local/wb_*"
DOTFILES="$DOTFILES $HOME/.config/niri/config.kdl"
DOTFILES="$DOTFILES $HOME/.config/niri/scripts"
DOTFILES="$DOTFILES $HOME/.config/nvim"
DOTFILES="$DOTFILES $HOME/.config/tmux/tmux.conf"
DOTFILES="$DOTFILES $HOME/.config/waybar"
DOTFILES="$DOTFILES $HOME/.bashrc"
DOTFILES="$DOTFILES $HOME/.merdely.profile"
DOTFILES="$DOTFILES $HOME/.vimrc"
DOTFILES="$DOTFILES $HOME/bin/gen-wm-help"
DOTFILES="$DOTFILES $HOME/bin/play_pause_media.sh"
DOTFILES="$DOTFILES $HOME/bin/rofi-launcher"
DOTFILES="$DOTFILES $HOME/bin/rofi-powermenu"
DOTFILES="$DOTFILES $HOME/bin/rofi-windows"
DOTFILES="$DOTFILES $HOME/bin/run-app-toggle"
DOTFILES="$DOTFILES $HOME/bin/run_terminal"
DOTFILES="$DOTFILES $HOME/bin/view-cheatsheet"
DOTFILES="$DOTFILES $HOME/bin/view-wm-help"
DOTFILES="$DOTFILES $HOME/bin/wm-closeapps"
DOTFILES="$DOTFILES $HOME/bin/wm-minimize"
DOTFILES="$DOTFILES $HOME/bin/yad-askpass"
DOTFILES="$DOTFILES /srv/scripts/bin/tmux_groupssh"
DOTFILES="$DOTFILES /srv/scripts/bin/tmux_reorder"
DOTFILES="$DOTFILES /srv/scripts/bin/tmux_winsplit"

dest_dir=$(dirname "$(realpath "$0")")

for dotfile in $DOTFILES; do
  relative_path=${dotfile/$HOME/}
  mkdir -p "$dest_dir""$(dirname "$relative_path")"
  rsync -a --info=NAME "$dotfile" "$dest_dir""$(dirname "$relative_path")"
done
