# Default in /ext/xdg/fuzzel/fuzzel.ini
font=monospace:size=16

[border]
width=2

[colors]
background=2d303bf2
border=4084d6ff

placeholder=c4cbd466
counter=c4cbd466

text=d4dbe4ff
prompt=d4dbe4ff
input=d4dbe4ff
match=d4dbe4ff
selection=4084d6ff
selection-text=d4dbe4ff
selection-match=ffffffff
