syntax enable                               " Syntax highlighting
set number                                  " Line numbers
set cursorline                              " Highlight current line
if has('termguicolors')
  set termguicolors                         " Enable 24-bit colors
endif
set background=dark
silent! colorscheme torte                   " Colorscheme
set colorcolumn=80                          " Column number where to show color column
set signcolumn=yes                          " Avoid text shifting when signs appear
set list                                    " Show list characters
set listchars=tab:»\ ,trail:·,nbsp:␣        " Specify list chars
set showmatch                               " Highlight matching brackets
set noshowmode                              " Don't show mode in command line
set tabstop=2                               " Tab width
set shiftwidth=2                            " Indent width
set softtabstop=2                           " Soft tab stop
set expandtab                               " Use spaces instead of tabs
set breakindent                             " Show wrapped lines indented
set ignorecase                              " Case insensitive search
set smartcase                               " Case sensitive if uppercase in search
set nowritebackup                           " Don't create backup before writing
set noswapfile                              " Don't create swap files
if has('persistent_undo')
  set undofile                              " Persistent undo
endif
set updatetime=250                          " Faster CursorHold / diagnostics
set path+=**                                " Include subdirectories in search
set wildignore+=*.o,*.obj,*.pyc,*.class,*.jar
set wildignore+=*/node_modules/*,*/.git/*,*/dist/*,*/build/*,*/.venv/*,*/__pycache__/*
set mouse=a                                 " Enable mouse support
set selection=inclusive                     " Include last char in selection
if has('clipboard')
  set clipboard^=unnamedplus                " Use system clipboard
endif
set splitbelow                              " Horizontal split creation position
set splitright                              " Vertical split creation position

" Reselect visual block after indent
vnoremap < <gv
vnoremap > >gv

" Open netrw Explorer
nnoremap - :Ex<CR>

augroup netrw_mappings
  autocmd!
  autocmd FileType netrw call s:NetrwMappings()
augroup END

function! s:NetrwMappings() abort
  " Can't use gb gd gf gF gg gh gn gp
  nnoremap <buffer> <Esc> :bd<CR>
  nnoremap <buffer> go :e<Space>
  nnoremap <buffer> g/ :e /<CR>
  nnoremap <buffer> gC :e $HOME/.config<CR>
  nnoremap <buffer> gE :e /etc<CR>
  nnoremap <buffer> gH :e $HOME<CR>
  nnoremap <buffer> gN :e $HOME/.vim<CR>
endfunction

" Highlight when yanking (copying) text
augroup highlight_yank
  autocmd!
  autocmd TextYankPost * silent! call timer_start(150, {-> execute('call clearmatches()')})
  autocmd TextYankPost * silent! let g:_yank_hl = matchadd('IncSearch', "\\%'[\\_.*\\%']")
augroup END

" --- Status Line ---

function! ModeIcon() abort
  let l:modes = {
        \ 'n':  'NORMAL',
        \ 'i':  'INSERT',
        \ 'v':  'VISUAL',
        \ 'V':  'V-LINE',
        \ "\<C-v>": 'V-BLOCK',
        \ 'c':  'COMMAND',
        \ 's':  'SELECT',
        \ 'S':  'S-LINE',
        \ "\<C-s>": 'S-BLOCK',
        \ 'R':  'REPLACE',
        \ 'r':  'REPLACE',
        \ '!':  'SHELL',
        \ 't':  'TERMINAL',
        \ }
  let l:mode = mode()
  return get(l:modes, l:mode, l:mode)
endfunction

function! StatuslinePercent() abort
  let l:current = line('.')
  let l:total = line('$')
  if l:current == 1
    return 'Top'
  elseif l:current == l:total
    return 'Bot'
  else
    return (l:current * 100 / l:total) . '%'
  endif
endfunction

set statusline=
set statusline+=\ %{ModeIcon()}
set statusline+=\ \|\ %f\ %h%m%r
set statusline+=%=
set statusline+=%{&fenc!=''?&fenc:&enc}
set statusline+=\ \|\ %{&fileformat}
set statusline+=\ \|\ %{&filetype}
set statusline+=\ \|\ %{StatuslinePercent()}
set statusline+=\|%l:%c
set statusline+=\ 
set laststatus=2
