syntax enable                               " Syntax highlighting
set nocompatible                            " Behave like vim
set number                                  " Line numbers
set cursorline                              " Highlight current line
set scrolloff=8                             " Number of lines to keep above/below cursor
if has('termguicolors')
  set termguicolors                         " Enable 24-bit colors
endif
set background=dark                         " Adjust the default color groups
colorscheme nightfly                        " Color scheme
function! s:ApplyHighlights() abort
  highlight Normal         ctermbg=NONE guibg=NONE
  highlight NormalNC       ctermbg=NONE guibg=NONE
  highlight EndOfBuffer    ctermbg=NONE guibg=NONE
  highlight StatusLine     gui=NONE cterm=NONE guifg=#c0c0d0 ctermfg=250 guibg=#081e2f ctermbg=17
  highlight StatusLineMode gui=bold cterm=bold guifg=#2c3043 ctermfg=250 guibg=#82aaff ctermbg=17
  highlight StatusLineGit  gui=NONE cterm=NONE guifg=#82aaff ctermfg=250 guibg=#2c3043 ctermbg=17
  highlight StatusLineIcon gui=NONE cterm=NONE guifg=#2c3043 ctermfg=250 guibg=#081e2f ctermbg=17
  highlight StatusLinePerc gui=NONE cterm=NONE guifg=#82aaff ctermfg=250 guibg=#2c3043 ctermbg=17
  highlight StatusLinePos  gui=NONE cterm=NONE guifg=#2c3043 ctermfg=250 guibg=#82aaff ctermbg=17
endfunction
call s:ApplyHighlights()
autocmd ColorScheme * call s:ApplyHighlights()
set colorcolumn=80                          " Column number where to show color column
set signcolumn=yes                          " Avoid text shifting when signs appear
set list                                    " Show list characters
set listchars=tab:»\ ,trail:·,nbsp:␣        " Specify list chars
set backspace=indent,eol,start              " Better backspace handling
set showmatch                               " Highlight matching brackets
set noshowmode                              " Don't show mode in command line
set tabstop=2                               " Tab width
set shiftwidth=2                            " Indent width
set softtabstop=2                           " Soft tab stop
set expandtab                               " Use spaces instead of tabs
set autoindent                              " Copy indent from previous8 line
set breakindent                             " Show wrapped lines indented
set incsearch                               " Search as you type
set hlsearch                                " Highlight matches
set ruler                                   " Show ruler
set ignorecase                              " Case insensitive search
set smartcase                               " Case sensitive if uppercase in search
set nowritebackup                           " Don't create backup before writing
set noswapfile                              " Don't create swap files
if has('persistent_undo')
  set undofile                              " Persistent undo
endif
set encoding=utf-8                          " Default encoding
set history=10000                           " Number of lines of history to remember
set ttimeoutlen=50                             " Escape key handling
set updatetime=250                          " Faster CursorHold / diagnostics
set shortmess=filnxtToOS                    " Avoid hit-enter prompts
set path+=**                                " Include subdirectories in search
set wildmenu                                " Command-line completion menu
set wildignore+=*.o,*.obj,*.pyc,*.class,*.jar
set wildignore+=*/node_modules/*,*/.git/*,*/dist/*,*/build/*,*/.venv/*,*/__pycache__/*
set mouse=a                                 " Enable mouse support
set selection=inclusive                     " Include last char in selection
if has('clipboard')
  set clipboard^=unnamedplus                " Use system clipboard
endif
set splitbelow                              " Horizontal split creation position
set splitright                              " Vertical split creation position

filetype plugin indent on                   " Load per file-type indent rules

let mapleader = " "                         " Set leader key
let maplocalleader = ","                    " Set local leader key

" Change/delete without clobbering the unnamed register
nnoremap c "_c
xnoremap c "_c
nnoremap C "_C
xnoremap C "_C
nnoremap x "_x
xnoremap x "_x

" Window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
if has('terminal')
  tnoremap <C-h> <C-w>h
  tnoremap <C-j> <C-w>j
  tnoremap <C-k> <C-w>k
  tnoremap <C-l> <C-w>l
endif
nnoremap <leader>sr <C-w>r
nnoremap <leader>sR <C-w>R
nnoremap <leader>sx <C-w>x
nnoremap <leader>sH <C-w>H
nnoremap <leader>sJ <C-w>J
nnoremap <leader>sK <C-w>K
nnoremap <leader>sL <C-w>L

" Move lines up/down
nnoremap <leader>j :m .+1<CR>==
nnoremap <leader>k :m .-2<CR>==
vnoremap <leader>j :m '>+1<CR>gv=gv
vnoremap <leader>k :m '<-2<CR>gv=gv

" Reselect visual block after indent
vnoremap < <gv
vnoremap > >gv

nnoremap <leader>; <Cmd>e #<CR>
nnoremap <leader>eh :Sexplore<CR>
nnoremap <leader>ev :Vexplore<CR>
nnoremap <leader>ss :syntax sync fromstart<CR>
nnoremap <leader>rc :edit $MYVIMRC<CR>
nnoremap <leader>rl :source $MYVIMRC<CR>

" Toggle copy-friendly mode
function! s:ToggleCopyFriendly() abort
  set cursorline! list! number! breakindent!
  if &colorcolumn ==# ''
    set colorcolumn=80
  else
    set colorcolumn=
  endif
  if &signcolumn ==# 'no'
    set signcolumn=yes
  else
    set signcolumn=no
  endif
endfunction
nnoremap <silent> <leader>cp :call <SID>ToggleCopyFriendly()<CR>

" Make current file executable
function! s:MakeExecutable() abort
  let l:file = expand('%:p')
  if l:file ==# ''
    echohl ErrorMsg | echom 'No file' | echohl None
    return
  endif
  write
  let l:result = system('chmod +x ' . shellescape(l:file))
  if v:shell_error != 0
    echohl ErrorMsg | echom 'chmod failed: ' . l:result | echohl None
    return
  endif
  edit!
  echom "Made '" . l:file . "' executable"
endfunction
nnoremap <leader>x :call <SID>MakeExecutable()<CR>

" Open netrw Explorer
nnoremap - :Ex<CR>

augroup netrw_mappings
  autocmd!
  autocmd FileType netrw call s:NetrwMappings()
augroup END

function! s:NetrwMappings() abort
  " Can't use gb gd gf gF gg gh gn gp
  nnoremap <buffer> <Esc> :bd<CR>
  nnoremap <buffer> go :e<Space>
  nnoremap <buffer> g/ :e /<CR>
  nnoremap <buffer> gC :e $HOME/.config<CR>
  nnoremap <buffer> gE :e /etc<CR>
  nnoremap <buffer> gH :e $HOME<CR>
  nnoremap <buffer> gN :e $HOME/.vim<CR>
endfunction

" Highlight when yanking (copying) text
" From https://www.statox.fr/posts/2020/07/vim_flash_yanked_text/
function! FlashYankedText()
    if (!exists('g:yankedTextMatches'))
        let g:yankedTextMatches = []
    endif
    let matchId = matchadd('IncSearch', ".\\%>'\\[\\_.*\\%<']..")
    let windowId = winnr()
    call add(g:yankedTextMatches, [windowId, matchId])
    call timer_start(200, 'DeleteTemporaryMatch')
endfunction
function! DeleteTemporaryMatch(timerId)
    while !empty(g:yankedTextMatches)
        let match = remove(g:yankedTextMatches, 0)
        let windowID = match[0]
        let matchID = match[1]
        try
            call matchdelete(matchID, windowID)
        endtry
    endwhile
endfunction
augroup highlightYankedText
    autocmd!
    autocmd TextYankPost * call FlashYankedText()
augroup END

" Return to last edit position when opening files
augroup restore_cursor
  autocmd!
  autocmd BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif
augroup END

" Resize splits when window is resized
augroup resize_splits
  autocmd!
  autocmd VimResized * tabdo wincmd =
augroup END

" Use 4 spaces for tabs with some filetypes
augroup filetype_indent
  autocmd!
  autocmd FileType python,php,markdown setlocal tabstop=4 shiftwidth=4
augroup END

" Prevent '#' from de-indenting in YAML files
augroup yaml_indentkeys
  autocmd!
  autocmd FileType yaml,yaml.ansible setlocal indentkeys-=0#
augroup END

" --- Status Line ---
function! ModeIcon() abort
  let l:modes = {
        \ 'n':  'NORMAL',
        \ 'i':  'INSERT',
        \ 'v':  'VISUAL',
        \ 'V':  'V-LINE',
        \ "\<C-v>": 'V-BLOCK',
        \ 'c':  'COMMAND',
        \ 's':  'SELECT',
        \ 'S':  'S-LINE',
        \ "\<C-s>": 'S-BLOCK',
        \ 'R':  'REPLACE',
        \ 'r':  'REPLACE',
        \ '!':  'SHELL',
        \ 't':  'TERMINAL',
        \ }
  let l:mode = mode()
  return get(l:modes, l:mode, l:mode)
endfunction

function! StatuslinePercent() abort
  let l:current = line('.')
  let l:total = line('$')
  if l:current == 1
    return 'Top'
  elseif l:current == l:total
    return 'Bot'
  else
    return (l:current * 100 / l:total) . '%'
  endif
endfunction

set statusline=%#StatusLineMode#
set statusline+=\ %{ModeIcon()}\ 
set statusline+=%#StatusLinePerc#
set statusline+=\ %f\ %h%m%r
set statusline+=%#StatusLine#
set statusline+=%=
set statusline+=%{&fenc!=''?&fenc:&enc}
set statusline+=\ \|\ %{&fileformat}
set statusline+=\ \|\ %{&filetype}\ 
set statusline+=%#StatusLinePerc#
set statusline+=\ %{StatuslinePercent()}\ 
set statusline+=%#StatusLineMode#
set statusline+=\ %l:%c\ 
set statusline+=%#StatusLine#
set laststatus=2
