-- vim: set filetype=lua :
-- NOTE: Do not edit this file directly
-- Use: chezmoi edit ~/.config/wezterm/mercury.lua
-- Or after editing, run: chezmoi re-add ~/.config/wezterm/mercury.lua

local M = {}

function M.apply(config)
  config.font_size = 11
end

return M
