# These variables will be imported by systemd and by ~/.bashrc

ELECTRON_OZONE_PLATFORM_HINT=auto
QT_QPA_PLATFORMTHEME=gtk3
QT_QPA_PLATFORMTHEME_QT6=gtk3
QT_QPA_PLATFORM=wayland
SSH_ASKPASS=yad-askpass
SSH_AUTH_SOCK=${XDG_RUNTIME_DIR:-/run/user/$EUID}/ssh-agent.socket
TERMINAL=kitty
