#!/usr/bin/env bash

options=(
  Lock
  Logout
  Reboot
  Shutdown/Halt
)

command=$(printf '%s\n' "${options[@]}" | fuzzel -d)

case "$command" in
  Lock) "$HOME"/.config/waybar/scripts/idle-inhibitor disable ; swaylock -f -c 000000 ;;
  Logout) "$HOME"/config/waybar/scripts/idle-inhibitor disable ; niri msg action quit ;;
  Reboot) "$HOME"/config/waybar/scripts/idle-inhibitor disable ; doas /sbin/reboot ;;
  Shutdown/Halt) "$HOME"/config/waybar/scripts/idle-inhibitor disable ; doas /sbin/halt -p ;;
  *) ;;
esac
