-- vim: set filetype=lua :
-- NOTE: Do not edit this file directly
-- Use: chezmoi edit ~/.config/nvim/lua/load_lspconfig.lua

do
  local lspconfig_loaded = pcall(require, 'lspconfig')
  if lspconfig_loaded then
    vim.api.nvim_create_autocmd('LspAttach', {
      group = vim.api.nvim_create_augroup('kickstart-lsp-attach', { clear = true }),
      callback = function(event)
        -- NOTE: Remember that Lua is a real programming language, and as such it is possible
        -- to define small helper and utility functions so you don't have to repeat yourself.
        --
        -- In this case, we create a function that lets us more easily define mappings specific
        -- for LSP related items. It sets the mode, buffer and description for us each time.
        local map = function(keys, func, desc, mode)
          mode = mode or 'n'
          vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = 'LSP: ' .. desc })
        end

        -- Rename the variable under your cursor.
        --  Most Language Servers support renaming across files, etc.
        map('grn', vim.lsp.buf.rename, 'Rename')

        -- Execute a code action, usually your cursor needs to be on top of an error
        -- or a suggestion from your LSP for this to activate.
        map('gra', vim.lsp.buf.code_action, 'Goto Code Action', { 'n', 'x' })

        -- WARN: This is not Goto Definition, this is Goto Declaration.
        --  For example, in C this would take you to the header.
        map('grD', vim.lsp.buf.declaration, 'Goto Declaration')

        -- The following two autocommands are used to highlight references of the
        -- word under your cursor when your cursor rests there for a little while.
        --    See `:help CursorHold` for information about when this is executed
        --
        -- When you move your cursor, the highlights will be cleared (the second autocommand).
        local client = vim.lsp.get_client_by_id(event.data.client_id)
        if client and client:supports_method('textDocument/documentHighlight', event.buf) then
          local highlight_augroup = vim.api.nvim_create_augroup('kickstart-lsp-highlight', { clear = false })
          vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
            buffer = event.buf,
            group = highlight_augroup,
            callback = vim.lsp.buf.document_highlight,
          })

          vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
            buffer = event.buf,
            group = highlight_augroup,
            callback = vim.lsp.buf.clear_references,
          })

          vim.api.nvim_create_autocmd('LspDetach', {
            group = vim.api.nvim_create_augroup('kickstart-lsp-detach', { clear = true }),
            callback = function(event2)
              vim.lsp.buf.clear_references()
              vim.api.nvim_clear_autocmds { group = 'kickstart-lsp-highlight', buffer = event2.buf }
            end,
          })
        end

        -- The following code creates a keymap to toggle inlay hints in your
        -- code, if the language server you are using supports them
        --
        -- This may be unwanted, since they displace some of your code
        -- if client and client:supports_method('textDocument/inlayHint', event.buf) then
        --   map('<leader>th', function() vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled { bufnr = event.buf }) end, 'Toggle Inlay Hints')
        -- end
      end,
    })

    ---@type table<string, vim.lsp.Config>
    local servers = {
      -- clangd = {},
      -- gopls = {},
      -- pyright = {},
      -- rust_analyzer = {},
      --
      -- Some languages (like typescript) have entire language plugins that can be useful:
      --    https://github.com/pmizio/typescript-tools.nvim
      --
      -- But for many setups, the LSP (`ts_ls`) will work just fine
      -- ts_ls = {},

      -- bashls = {},
      ruff = {},
      pylsp = {
        settings = {
          pylsp = {
            plugins = {
              pyflakes = { enabled = false },
              pycodestyle = { enabled = false },
              autopep8 = { enabled = false },
              yapf = { enabled = false },
              mccabe = { enabled = false },
              pylsp_mypy = { enabled = false },
              pylsp_black = { enabled = false },
              pylsp_isort = { enabled = false },
            },
          },
        },
      },

      -- Special Lua Config, as recommended by neovim help docs
      lua_ls = {
        on_init = function(client)
          client.server_capabilities.documentFormattingProvider = false -- Disable formatting (formatting is done by stylua)

          if client.workspace_folders then
            local path = client.workspace_folders[1].name
            if path ~= vim.fn.stdpath 'config' and (vim.uv.fs_stat(path .. '/.luarc.json') or vim.uv.fs_stat(path .. '/.luarc.jsonc')) then return end
          end

          client.config.settings.Lua = vim.tbl_deep_extend('force', client.config.settings.Lua, {
            runtime = {
              version = 'LuaJIT',
              path = { 'lua/?.lua', 'lua/?/init.lua' },
            },
            workspace = {
              checkThirdParty = false,
              -- NOTE: this is a lot slower and will cause issues when working on your own configuration.
              --  See https://github.com/neovim/nvim-lspconfig/issues/3189
              library = vim.tbl_extend('force', vim.api.nvim_get_runtime_file('', true), {
                '${3rd}/luv/library',
                '${3rd}/busted/library',
              }),
            },
          })
        end,
        ---@type lspconfig.settings.lua_ls
        settings = {
          Lua = {
            format = { enable = false }, -- Disable formatting (formatting is done by stylua)
          },
          telemetry = { enable = false, },
        },
      },
    }

    local ensure_installed = vim.tbl_keys(servers or {})
    if vim.fn.executable 'npm' == 1 then
      servers.bashls = {}
      servers.yamlls = {}
      vim.list_extend(ensure_installed, {
        "bashls",
        "yamlls",
      })
    else
      servers.efm = {
        filetypes = { 'sh', 'bash', 'yaml' },
        init_options = { documentFormatting = true, documentRangeFormatting = true },
        settings = {
          -- logFile = '/tmp/efm.log',
          -- logLevel = 5,
          rootMarkers = { '.git/', '.' },
          languages = {
            sh = {
              {
                lintCommand = 'shellcheck -f gcc -x -',
                lintStdin = true,
                lintIgnoreExitCode = true,
                lintSource = 'shellcheck',
                lintFormats = {
                  '%f:%l:%c: %trror: %m',
                  '%f:%l:%c: %tarning: %m',
                  '%f:%l:%c: %tote: %m',
                },
              },
              { formatCommand = 'shfmt -i 2 -ci', formatStdin = true },
            },
            yaml = {
              { lintCommand = 'yamllint -f parsable -', lintStdin = true, lintIgnoreExitCode = true, lintSource = 'yamllint' },
              { formatCommand = 'yamlfmt -', formatStdin = true },
            },
          },
        },
      }
      vim.list_extend(ensure_installed, {
        'efm',
        'yamlfmt',
        'yamllint',
      })
    end
    if vim.fn.executable 'unzip' == 1 then
      if vim.uv.os_uname().machine == "x86_64" then
        servers.qmlls = {}
        vim.list_extend(ensure_installed, { "qmlls" })
      end
      servers.stylua = {}
      vim.list_extend(ensure_installed, { "stylua" })
    end

    -- Automatically install LSPs and related tools to stdpath for Neovim
    do
      local mason_installed = pcall(require, 'mason')
      if mason_installed then
        require('mason').setup {}

        -- Ensure the servers and tools above are installed
        --
        -- To check the current status of installed tools and/or manually install
        -- other tools, you can run
        --    :Mason
        --
        -- You can press `g?` for help in this menu.
        vim.list_extend(ensure_installed, {
          -- You can add other tools here that you want Mason to install
          'shellcheck',
          'shfmt',
        })

        local mason_tool_installer_installed = pcall(require, 'mason-tool-installer')
        if mason_tool_installer_installed then
          require('mason-tool-installer').setup { ensure_installed = ensure_installed }
        end

        for name, server in pairs(servers) do
          vim.lsp.config(name, server)
          vim.lsp.enable(name)
        end
      end
    end
  end
end
