cameras[garagedoorcam]="rtsp://camera:{{ pass "systems/frigate/rtsp" }}@frigate.erdely.in:8554/garagedoorcam"
cameras[backyardcam]="rtsp://frigate:{{ pass "systems/cameras/frigate" }}@backyardcam.erdely.in:554"
cameras[backyard2cam]="rtsp://frigate:{{ pass "systems/cameras/frigate" }}@backyard2cam.erdely.in:554"
cameras[chimneycam]="rtsp://frigate:{{ pass "systems/cameras/frigate" }}@chimneycam.erdely.in:554"
cameras[frontdoorcam]="rtsp://frigate:{{ pass "systems/cameras/frigate" }}@frontdoorcam.erdely.in:554"
cameras[frontdoor2cam]="rtsp://frigate:{{ pass "systems/cameras/frigate" }}@frontdoor2cam.erdely.in:554"
cameras[garagecam]="rtsp://frigate:{{ pass "systems/cameras/frigate" }}@garagecam.erdely.in:554"
cameras[shedcam]="rtsp://frigate:{{ pass "systems/cameras/frigate" }}@shedcam.erdely.in:554"
