# vim: set filetype=conf :

bw_entry="EmpireTech IP Cameras - frigate"
bw_entries[garagedoorcam]="Frigate - rtsp"

cameras[garagedoorcam]="rtsp://\${auth_garagedoorcam}frigate.erdely.in:8554/garagedoorcam"
cameras[backyardcam]="rtsp://\${default_auth}backyardcam.erdely.in:554"
cameras[backyard2cam]="rtsp://\${default_auth}backyard2cam.erdely.in:554"
cameras[chimneycam]="rtsp://\${default_auth}chimneycam.erdely.in:554"
cameras[frontdoorcam]="rtsp://\${default_auth}frontdoorcam.erdely.in:554"
cameras[frontdoor2cam]="rtsp://\${default_auth}frontdoor2cam.erdely.in:554"
cameras[garagecam]="rtsp://\${default_auth}garagecam.erdely.in:554"
cameras[shedcam]="rtsp://\${default_auth}shedcam.erdely.in:554"
