# Settings
# alias[alias]=repo
# pkg[repo]='/regex_with_{SYSTEM}_{ARCH}_{STDLIB}\.file\.type$'
# srcbin[repo]='regex_with_{SYSTEM}-{ARCH}'
# bin[repo]='a_file_that_does_not_match_repo_portion_of_repo'

# pkg[twpayne/chezmoi]='/chezmoi_.*_{SYSTEM}_{ARCH}'
# bin[twpayne/chezmoi]=chezmoi

alias[chezmoi]=twpayne/chezmoi
alias[jqp]=noahgorstein/jqp
alias[lazydocker]=jesseduffield/lazydocker

alias[alloy]=grafana/alloy
pkg[grafana/alloy]='/alloy-{SYSTEM}-{ARCH}\.zip$'
srcbin[grafana/alloy]='alloy-{SYSTEM}-{ARCH}'

alias[atuin]=atuinsh/atuin
pkg[atuinsh/atuin]='/atuin-{ARCH}-unknown-{SYSTEM}-{STDLIB}\.tar\.gz$'

types[logseq/logseq]=appimage

bin[neovim/neovim]=nvim
types[neovim/neovim]=appimage

alias[netbird]=netbirdio/netbird
pkg[netbirdio/netbird]=/netbird_[0-9.-]+_{SYSTEM}_{ARCH}.tar.gz

alias[shfmt]=mvdan/sh
pkg[mvdan/sh]='/shfmt_.*_{SYSTEM}_{ARCH}$'
bin[mvdan/sh]=shfmt

# bin[VictoriaMetrics/VictoriaMetrics]=victoria-metrics-prod
# alias[VictoriaLogs]=VictoriaMetrics/VictoriaLogs
# bin[VictoriaMetrics/VictoriaLogs]=victoria-logs-prod
# alias[VictoriaTraces]=VictoriaMetrics/VictoriaTraces
# bin[VictoriaMetrics/VictoriaTraces]=victoria-traces-prod
# alias[vlagent]=VictoriaMetrics/VictoriaLogs
# pkg[VictoriaMetrics/VictoriaLogs]='/shfmt_.*_{SYSTEM}_{ARCH}$'
