# Settings
# alias[alias]=repo
# regex[repo]='/regex_with_{SYSTEM}_{ARCH}_{STDLIB}\.file\.type$'
# srcbin[repo]='regex_with_{SYSTEM}-{ARCH}'
# bin[repo]='a_file_that_does_not_match_repo_portion_of_repo'
# type[repo]=(tarball|zipfile|deb|rpm|pacman|appimage)

# regex[twpayne/chezmoi]='/chezmoi_.*_{SYSTEM}_{ARCH}'
# bin[twpayne/chezmoi]=chezmoi

alias[chezmoi]=twpayne/chezmoi
alias[jqp]=noahgorstein/jqp
alias[lazydocker]=jesseduffield/lazydocker

alias[alloy]=grafana/alloy
regex[alloy]='/alloy-{SYSTEM}-{ARCH}\.zip$'
srcbin[alloy]='alloy-{SYSTEM}-{ARCH}'
dest[alloy]=/usr/local/sbin
sudo[alloy]=true

alias[atuin]=atuinsh/atuin
regex[atuin]='/atuin-{ARCH}-unknown-{SYSTEM}-{STDLIB}\.tar\.gz$'

type[logseq]=appimage

bin[neovim]=nvim
type[neovim]=appimage

alias[netbird]=netbirdio/netbird
regex[netbird]=/netbird_[0-9.-]+_{SYSTEM}_{ARCH}.tar.gz
dest[netbird]=/usr/local/sbin
sudo[netbird]=true

alias[shfmt]=mvdan/sh
regex[shfmt]='/shfmt_.*_{SYSTEM}_{ARCH}$'
bin[shfmt]=shfmt

alias[VictoriaLogs]=VictoriaMetrics/VictoriaLogs
bin[VictoriaLogs]=victoria-logs-prod
regex[VictoriaLogs]='/victoria-logs-{SYSTEM}-{ARCH}-v[0-9.]+\.tar\.gz$'
dest[VictoriaLogs]=/usr/local/sbin
sudo[VictoriaLogs]=true

bin[VictoriaMetrics]=victoria-metrics-prod
regex[VictoriaMetrics]='/victoria-metrics-{SYSTEM}-{ARCH}-v[0-9.]+\.tar\.gz$'
dest[VictoriaMetrics]=/usr/local/sbin
sudo[VictoriaMetrics]=true

alias[VictoriaTraces]=VictoriaMetrics/VictoriaTraces
bin[VictoriaTraces]=victoria-traces-prod
dest[VictoriaTraces]=/usr/local/sbin
sudo[VictoriaTraces]=true

alias[vmagent]=VictoriaMetrics/VictoriaMetrics
regex[vmagent]='/vmutils-{SYSTEM}-{ARCH}-v[0-9.]+\.tar\.gz$'
bin[vmagent]=vmagent-prod
dest[vmagent]=/usr/local/sbin
sudo[vmagent]=true

alias[vmauth]=VictoriaMetrics/VictoriaMetrics
regex[vmauth]='/vmutils-{SYSTEM}-{ARCH}-v[0-9.]+\.tar\.gz$'
bin[vmauth]=vmauth-prod
dest[vmauth]=/usr/local/sbin
sudo[vmauth]=true

alias[vlagent]=VictoriaMetrics/VictoriaLogs
regex[vlagent]='/vlutils-{SYSTEM}-{ARCH}-v[0-9.]+\.tar\.gz$'
bin[vlagent]=vlagent-prod
dest[vlagent]=/usr/local/sbin
sudo[vlagent]=true

alias[vector]=vectordotdev/vector
regex[vector]='/vector-[0-9.]+-{ARCH}-unknown-{SYSTEM}-gnu\.tar\.gz$'
release_search[vector]='v[0-9][^"]*'
bin[vector]=vector
type[vector]=tarball
